library(shiny)
# Define UI for dataset viewer application
shinyUI(pageWithSidebar(

  # Application title
  headerPanel("Hydrophobicity Scores"),
  
  # Sidebar with controls to select a dataset and specify the number
  # of observations to view
  sidebarPanel(
    tags$head(
      tags$style("body {background-color: silver; }")
    )
    ,selectInput("sequence", "Choose one of the following proteins:", 
                choices = c("-------------------------------", "Glycophorin A" = 'MYGKIIFVLLLSEIVSISASSTTGVAMHTSTSSSVTKSYISSQTNDTHKRDTYAATPRAHEVSEISVRTVYPPEEETGERVQLAHHFSEPEITLIIFGVMAGVIGTILLISYGIRRLIKKSPSDVKPLPSPDTDVPLSSVEIENPETSD',
                            "Bacteriorhodopsin" = "MQAQITGRPEWIWLALGTALMGLGTLYFLVKGMGVSDPDAKKFYAITTLVPAIAFTMYLSMLLGYGLTMVPFGGEQNPIYWARYADWLFTTPLLLLDLALLVDADQGTILALVGADGIMIGTGLVGALTKVYSYRFVWWAISTAAMLYILYVLFFGFTSKAESMRPEVASTFKVLRNVTVVLWSAYPVVWLIGSEGAGIVPLNIETLLFMVLDVSAKVGFGLILLRSRAIFGEAEAPEPSAGDGAAATS",
                            "Scramblase" = "MKSNVNQGGYAPPGFGSGFQPNAPPAEGFGYPPPTGGHNAPYPPAPGHPQPPPPTNYGFMPGPQPAGYAPVPQMPPYGEAPPYGAGQPPYMGGPGGQPPYAGGPGGQPPYVGGPGGQPHYGGGAPPPQAFGGYPPGPAGPGGPPNAFGGYPPGQPQQPIVTQPGMGPGMGPGMAPQGGPAGDWMSIPTGIPNCPRGLEYLTTIDQLLVKQKVELLEAFTGFETNNKFTIKNALGQKVYFAAEDNDCCTRNCCGPARPFDMRVFDNFQQEVIHMHRPLACSSCLFPCCLQSIEVSAPPGNVIGTIEQEWSICSPSFRILNHVGDTVMRIEGPFCTFSLCGDVEFNVVSLTGEKIGKISKQWSGLAREIFTDADFFGINFPLDLDVRMKAVLLGATFLIDAMFFEKAGNQETDRPGML"))  
  
    ,textInput("sequence2", "Or enter any protein sequence:", ""), submitButton("Go!")
    ),
  
  
  # Show a summary of the dataset and an HTML table with the requested
  # number of observations
  mainPanel(
    plotOutput("summary")
    #plotOutput("summary2")
  )
)) 