library(shiny)

# Define UI for dataset viewer application
shinyUI(pageWithSidebar(
  
  # Application title
  headerPanel("Hydrophobicity Scores"),
  
  # Sidebar with controls to select a dataset and specify the number
  # of observations to view
  sidebarPanel(
    selectInput("sequence", "Choose a protein:", 
                choices = c("Glycophorin A" = 'MYGKIIFVLLLSEIVSISASSTTGVAMHTSTSSSVTKSYISSQTNDTHKRDTYAATPRAHEVSEISVRTVYPPEEETGERVQLAHHFSEPEITLIIFGVMAGVIGTILLISYGIRRLIKKSPSDVKPLPSPDTDVPLSSVEIENPETSD',
                            "Bacteriorhodopsin" = "MQAQITGRPEWIWLALGTALMGLGTLYFLVKGMGVSDPDAKKFYAITTLVPAIAFTMYLSMLLGYGLTMVPFGGEQNPIYWARYADWLFTTPLLLLDLALLVDADQGTILALVGADGIMIGTGLVGALTKVYSYRFVWWAISTAAMLYILYVLFFGFTSKAESMRPEVASTFKVLRNVTVVLWSAYPVVWLIGSEGAGIVPLNIETLLFMVLDVSAKVGFGLILLRSRAIFGEAEAPEPSAGDGAAATS",
                            "Scramblase" = "MKSNVNQGGYAPPGFGSGFQPNAPPAEGFGYPPPTGGHNAPYPPAPGHPQPPPPTNYGFMPGPQPAGYAPVPQMPPYGEAPPYGAGQPPYMGGPGGQPPYAGGPGGQPPYVGGPGGQPHYGGGAPPPQAFGGYPPGPAGPGGPPNAFGGYPPGQPQQPIVTQPGMGPGMGPGMAPQGGPAGDWMSIPTGIPNCPRGLEYLTTIDQLLVKQKVELLEAFTGFETNNKFTIKNALGQKVYFAAEDNDCCTRNCCGPARPFDMRVFDNFQQEVIHMHRPLACSSCLFPCCLQSIEVSAPPGNVIGTIEQEWSICSPSFRILNHVGDTVMRIEGPFCTFSLCGDVEFNVVSLTGEKIGKISKQWSGLAREIFTDADFFGINFPLDLDVRMKAVLLGATFLIDAMFFEKAGNQETDRPGML"))  
  ),
  
  # Show a summary of the dataset and an HTML table with the requested
  # number of observations
  mainPanel(
    plotOutput("summary")
  )
)) 